version: '2'
services:
  node:
    build:
      context: ./node
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
        no_proxy: localhost,fess
    volumes:
      - ./node:/root/node
      - /root/node/fess-app/node_modules/
      - /root/node/fess-app/client/node_modules/
    ports:
      - 8887:2999
      - 8888:3000
    depends_on:
      - fess
    networks:
      - esnet
  fess:
    build:
      context: ./fess
      args:
        FESS_VERSION: "11.3.1"
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    restart: always
    ports:
      - "8889:8080"
    depends_on:
      - elasticsearch
    environment:
      ES_HTTP_URL: "http://elasticsearch:9200"
      ES_TRANSPORT_URL: "elasticsearch:9300"
      FESS_DICTIONARY_PATH: "/var/lib/elasticsearch/config/"
    dns: 172.19.1.34
    networks:
      - esnet
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
        ftp_proxy: ${HTTPS_PROXY}
        all_proxy: ${HTTPS_PROXY}
        ELASTIC_VERSION: "5.5.2"
        ES_DOWNLOAD_URL: "https://artifacts.elastic.co/downloads/elasticsearch"
        ES_JAVA_OPTS: "-Xms2g -Xmx2g -Dhttp.proxyHost=tkyproxy.intra.tis.co.jp -Dhttp.proxyPort=8080 -Dhttps.proxyHost=tkyproxy.intra.tis.co.jp -Dhttps.proxyPort=8080"
    restart: always
    cap_add:
      - IPC_LOCK
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/var/lib/elasticsearch
    dns: 172.19.1.34
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge
